### ISSUE TITLE
SWR reading did not match with external meter

### ISSUE THREAD

**Issue by DH1KLM** [n1gp/Anvelina_PROIII#1]
I use the Anvelina SDR board together with an original ANAN100D/200D PA board. REV24 and also REV15

I have problems with the displayed FWD/REV values in Thetis, resulting in an absolutely nonsensical SWR display.
No matter which TRX is selected in the setup, the SWR display never matches.
It's certainly not the PA board, I have 3 of them and none of them display the SWR correctly in Thetis.

As a quick and drity fix I have modified the Thetis source code slightly in the relevant area in order to obtain reasonably useful values.

Is it possible that the Anvelina firmware differs from the original Orion firmware in this relevant part?

**Comment by Aicene** [comment]
Yuri comented on this, that is not firmware problem. I'll sent you a mail.

**Comment by DH1KLM** [comment]
Obviously not an ANVELINA related problem. It's more the interaction of the ANAN 100D/200D PA board with ANVELINA.
The combination ORION MKII together with ANAN 100D/200D PA is neither supported by Thetis (ANAN7000/8000 setting) nor the firmware. (It was never planned that way).

The PA works with ANVELINA without any problems, the RF power readout also works (after adapting the source code), only FWD/REV cause problems.

Issue closed for now.
